import type { AppId, Preferences, WorkspaceFile } from './types';

export const APPS: { id: AppId; name: string; description: string; color: string }[] = [
  {
    id: 'explorer',
    name: 'File Explorer',
    description: 'Everything in its place',
    color: '#e6b24e',
  },
  { id: 'browser', name: 'Browser', description: 'A world of possibilities', color: '#418cd9' },
  { id: 'notes', name: 'Notes', description: 'A home for your ideas', color: '#e1a371' },
  { id: 'photos', name: 'Photos', description: 'The moments that matter', color: '#89ad91' },
  { id: 'music', name: 'Music', description: 'Find your everyday rhythm', color: '#af8dc9' },
  { id: 'terminal', name: 'Terminal', description: 'A little more control', color: '#526e62' },
  { id: 'settings', name: 'Settings', description: 'Make yourself at home', color: '#97a3ad' },
  { id: 'calculator', name: 'Calculator', description: 'It all adds up', color: '#729999' },
  { id: 'calendar', name: 'Calendar', description: 'Make time for what matters', color: '#d87e6b' },
  { id: 'weather', name: 'Weather', description: 'A little look outside', color: '#dfb453' },
  { id: 'focus', name: 'Focus', description: 'One thing at a time', color: '#9fac86' },
];
export const WALLPAPERS = [
  {
    id: 'serenity',
    name: 'Quiet hills',
    description: 'A breath of fresh air',
    url: '/wallpapers/serenity.jpg',
    color: '#477563',
  },
  {
    id: 'dusk',
    name: 'Coastal hour',
    description: 'Somewhere, by the sea',
    url: '/wallpapers/dusk.jpg',
    color: '#b18989',
  },
  {
    id: 'bloom',
    name: 'Soft forms',
    description: 'Room for a new perspective',
    url: '/wallpapers/bloom.jpg',
    color: '#9aa3c9',
  },
];
export const DEFAULT_PREFS: Preferences = {
  name: 'Local account',
  theme: 'light',
  wallpaper: '/wallpapers/serenity.jpg',
  accent: '#47745b',
  transparency: true,
  animations: true,
  brightness: 100,
  volume: 65,
  wifi: true,
  bluetooth: false,
  airplane: false,
  focus: false,
  largeIcons: false,
  city: 'Da Nang',
};
const now = Date.now();
export const SEED_FILES: WorkspaceFile[] = [
  {
    id: 'documents',
    name: 'Documents',
    kind: 'folder',
    parentId: 'root',
    modified: now,
    size: 0,
    color: 'yellow',
  },
  {
    id: 'pictures',
    name: 'Pictures',
    kind: 'folder',
    parentId: 'root',
    modified: now,
    size: 0,
    color: 'green',
  },
  {
    id: 'music-folder',
    name: 'Music',
    kind: 'folder',
    parentId: 'root',
    modified: now,
    size: 0,
    color: 'purple',
  },
  {
    id: 'downloads',
    name: 'Downloads',
    kind: 'folder',
    parentId: 'root',
    modified: now,
    size: 0,
    color: 'blue',
  },
  {
    id: 'projects',
    name: 'Projects',
    kind: 'folder',
    parentId: 'documents',
    modified: now,
    size: 0,
    color: 'orange',
  },
  {
    id: 'welcome-note',
    name: 'A little space for big ideas.md',
    kind: 'text',
    parentId: 'documents',
    modified: now - 60000,
    size: 612,
    favorite: true,
    content:
      '# A little space for big ideas\n\nWelcome to Window React — your own little corner of the internet.\n\nA familiar feeling, with a fresh perspective. No noise. No rush. Just a little more room for the things you love.\n\n## Make yourself at home\n\n- Collect your thoughts in Notes\n- Find your rhythm with an original ambient playlist\n- Pick a wallpaper that feels like you\n- Set aside 25 minutes for a little focused work\n\n## The small details\n\nYour notes, files, and preferences are saved in this browser automatically. No account needed.\n\nPress **Ctrl + K** to find anything. Double-click a title bar to maximize a window. Drag a window to the edge to snap it.\n\nHere’s to making something wonderful.\n\n— Your friends at Window React',
  },
  {
    id: 'ideas-note',
    name: 'Things worth making.md',
    kind: 'text',
    parentId: 'documents',
    modified: now - 3600000,
    size: 284,
    content:
      '# Things worth making\n\nA running list of little possibilities.\n\n- A playlist for slow Sunday mornings\n- A photo journal of places that feel like home\n- That side project I keep thinking about\n- A really good cup of coffee\n\n## A thought for today\n\nThe best way to begin is simply to begin.\n',
  },
  {
    id: 'readme-file',
    name: 'hello-world.js',
    kind: 'code',
    parentId: 'projects',
    modified: now - 86400000,
    size: 129,
    content:
      '// A fresh start. An open window.\n\nconst greeting = "Hello, world!";\nconsole.log(greeting);\n\n// What will you make today?\n',
  },
  ...WALLPAPERS.map((wallpaper, i): WorkspaceFile => ({
    id: `photo-${wallpaper.id}`,
    name: `${wallpaper.name}.jpg`,
    kind: 'image',
    parentId: 'pictures',
    url: wallpaper.url,
    modified: now - i * 7200000 - 120000,
    size: 1024 * (630 + i * 117),
    favorite: i === 0,
  })),
  {
    id: 'audio-0',
    name: 'Slow mornings.wav',
    kind: 'audio',
    parentId: 'music-folder',
    url: '/audio/slow-mornings.wav',
    modified: now - 240000,
    size: 3175244,
    favorite: true,
  },
  {
    id: 'audio-1',
    name: 'Somewhere, softer.wav',
    kind: 'audio',
    parentId: 'music-folder',
    url: '/audio/somewhere-softer.wav',
    modified: now - 86400000,
    size: 3704444,
  },
  {
    id: 'audio-2',
    name: 'A quiet kind of blue.wav',
    kind: 'audio',
    parentId: 'music-folder',
    url: '/audio/quiet-blue.wav',
    modified: now - 172800000,
    size: 4233644,
  },
];
export const TRACKS = [
  {
    id: 'audio-0',
    title: 'Slow mornings',
    artist: 'Window Sessions',
    album: 'A little room to breathe',
    url: '/audio/slow-mornings.wav',
    artwork: '/wallpapers/serenity.jpg',
    duration: 72,
    color: '#526d50',
  },
  {
    id: 'audio-1',
    title: 'Somewhere, softer',
    artist: 'Window Sessions',
    album: 'A little room to breathe',
    url: '/audio/somewhere-softer.wav',
    artwork: '/wallpapers/dusk.jpg',
    duration: 84,
    color: '#b57d87',
  },
  {
    id: 'audio-2',
    title: 'A quiet kind of blue',
    artist: 'Window Sessions',
    album: 'A little room to breathe',
    url: '/audio/quiet-blue.wav',
    artwork: '/wallpapers/bloom.jpg',
    duration: 96,
    color: '#8890b9',
  },
];
export const APP_SIZES: Record<AppId, [number, number]> = {
  explorer: [1060, 726],
  browser: [1040, 700],
  notes: [880, 650],
  music: [920, 630],
  terminal: [800, 525],
  photos: [950, 650],
  settings: [900, 666],
  calculator: [380, 575],
  calendar: [850, 650],
  weather: [860, 650],
  focus: [690, 595],
};
